version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'sh -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0" '
        volumes:
            - .:/app
        ports:
            - 8000:8000